server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:rulesdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
